eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true

okta:
  oauth2:
    issuer: https://dev-18359154.okta.com/oauth2/default
    audience: api://default
spring:
  zipkin:
    baseUrl: http://zipkin-svc:9411    
    
  
